### ISSUE TITLE
Not playing m3u8 files

### ISSUE THREAD

**Issue by go2hyder** [frontyard/cordova-exoplayer-plugin#1]
I met some problem with plugin. When i try to play m3u8 audio files its not playing.My code is like this

`$scope.playFMM = function() {
    var params = {
        type: "dash",
        user_agent: "PluginExoPlayer",
        plugin_controls_visible: true, 
        header: { 
            height: 200,
            padding: 30,
            background_color: "#33F0F8FF",
            image_url: "https://s-media-cache-ak0.pinimg.com/originals/77/7a/df/777adf082fc125aa9490a3450192ec6c.jpg",
            text_color: "#BBFAA8EF",
            text_align: "center",
            text: "Lorem ipsum Ipsum\nlorem Lorem",
            text_size: 20
        },
        url: "http://partlive.appscp.com:1935/live/general/playlist.m3u8",
        full_screen: true,
        aspect_ratio: "fit_screen",
        raw_touch_events: false
    }
    var player = exoplayer.init(params);
    player.show(function(success) {
        console.log("success", success)
    }, function(err) {
        console.log("err", err)
    })
}`

**Comment by frontyard** [comment]
Have you tried your stream in another dash player and confirmed it works?

**Comment by go2hyder** [comment]
Yes It is working perfectly on cordova vitameo plugin.But unfortunately google playstore reject the app because of that plugin.

**Comment by frontyard** [comment]
I noticed you're telling the player your stream is 'dash' but it looks like you're using hls.

Change type parameter to 'hls'.

**Comment by go2hyder** [comment]
I have tried with hls also..But not working

**Comment by frontyard** [comment]
I just tried your stream in my player and it works fine.

Can you check if you have any errors/exception in both Cordova and Android.

For Cordova connect to you device via USB, open Chrome and type chrome://inspect, then connect to the device.

For Android run adb logcat.

**Comment by frontyard** [comment]
Also can you try with somewhat simplified config:

`$scope.playFMM = function() {
    var params = {
    	type: 'hls',
        url: "http://partlive.appscp.com:1935/live/general/playlist.m3u8",
        user_agent: "PluginExoPlayer",
	plugin_controls_visible: false,
    	aspect_ratio: 'fill_screen',
        full_screen: true,
        raw_touch_events: false
    }
    var player = exoplayer.init(params);
    player.show(function(success) {
        console.log("success", success)
    }, function(err) {
        console.log("err", err)
    })
}`

**Comment by go2hyder** [comment]
Ok..Let me check it

**Comment by go2hyder** [comment]
Yes it is working now.Thanks bro..

**Comment by go2hyder** [comment]
But can I play with streaming url other than m3u8. For example I tried this url `http://s8.viastreaming.net:7850/`  But its not playing

**Comment by go2hyder** [comment]
I have tried both hls and dash.  Is there any other type?.
Because this is working fine in html audio tag..

**Comment by frontyard** [comment]
I'm adding support for regular media files (as long as they're supported by ExoPlayer). I'll let you know when you can try.

**Comment by go2hyder** [comment]
Ok

**Comment by frontyard** [comment]
I've added support for all the stream types ExoPlayer support. Please try again (make sure you remove/add the plugin to pull in latest version).

**Comment by go2hyder** [comment]
@frontyard .Its working fine.Thank you so much bro..
Please update your Readme.md also..So that people can use that.
