### ISSUE TITLE
Problem Build Ionic 5

### ISSUE THREAD

**Issue by gfernandez87** [frontyard/cordova-exoplayer-plugin#101]
When trying to do the build it returns the following errors, please help

Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     D:\R1\ionic\app-radio\app\platforms\android\app\src\main\res\layout\exo_playback_control_view.xml:19: AAPT: error: resource id/exo_rew (aka ..:id/exo_rew) not found.

     D:\R1\ionic\app-radio\app\platforms\android\app\src\main\res\layout\exo_playback_control_view.xml:22: AAPT: error: resource id/exo_play (aka ..:id/exo_play) not found.

     D:\R1\ionic\app-radio\app\platforms\android\app\src\main\res\layout\exo_playback_control_view.xml:25: AAPT: error: resource id/exo_pause 
(aka ..:id/exo_pause) not found.

     D:\R1\ionic\app-radio\app\platforms\android\app\src\main\res\layout\exo_playback_control_view.xml:28: AAPT: error: resource id/exo_ffwd (aka ..:id/exo_ffwd) not found.

     D:\R1\ionic\app-radio\app\platforms\android\app\src\main\res\layout\exo_playback_control_view.xml:97: AAPT: error: resource id/exo_position (aka ..:id/exo_position) not found.

     D:\R1\ionic\app-radio\app\platforms\android\app\src\main\res\layout\exo_playback_control_view.xml:106: AAPT: error: attribute buffered_color (aka ..:buffered_color) not found.

     D:\R1\ionic\app-radio\app\platforms\android\app\src\main\res\layout\exo_playback_control_view.xml:106: AAPT: error: attribute played_color (aka ..:played_color) not found.

     D:\R1\ionic\app-radio\app\platforms\android\app\src\main\res\layout\exo_playback_control_view.xml:106: AAPT: error: resource id/exo_progress (aka ..:id/exo_progress) not found.

     D:\R1\ionic\app-radio\app\platforms\android\app\src\main\res\layout\exo_playback_control_view.xml:114: AAPT: error: resource id/exo_duration (aka ..:id/exo_duration) not found.

     D:\R1\ionic\app-radio\app\platforms\android\app\src\main\res\layout\exo_simple_player_view.xml:18: AAPT: error: resource id/exo_content_frame (aka ..:id/exo_content_frame) not found.

     D:\R1\ionic\app-radio\app\platforms\android\app\src\main\res\layout\exo_simple_player_view.xml:25: AAPT: error: resource id/exo_shutter (aka ..:id/exo_shutter) not found.

     D:\R1\ionic\app-radio\app\platforms\android\app\src\main\res\layout\exo_simple_player_view.xml:30: AAPT: error: resource id/exo_artwork (aka ..:id/exo_artwork) not found.

     D:\R1\ionic\app-radio\app\platforms\android\app\src\main\res\layout\exo_simple_player_view.xml:35: AAPT: error: resource id/exo_subtitles (aka ..:id/exo_subtitles) not found.

     D:\R1\ionic\app-radio\app\platforms\android\app\src\main\res\layout\exo_simple_player_view.xml:42: AAPT: error: resource id/exo_controller_placeholder (aka ..:id/exo_controller_placeholder) not found.

**Comment by frontyard** [comment]
I don't support IONIC directly I believe someone else has done that.
