### ISSUE TITLE
Audio cuts out after a few minutes of audio playback

### ISSUE THREAD

**Issue by gfernandez87** [frontyard/cordova-exoplayer-plugin#103]
I am having problems with some devices when I am playing m3u8 live audio, after approximately 30 minutes the audio is cut off and the following exception is thrown, can someone help me solve or contemplate this problem.

errorMessage: null
errorType: "SOURCE"
eventType: "PLAYER_ERROR_EVENT"
stackTrace: "co.frontyard.cordova.plugin.exoplayer.Payload#playerErrorEvent@182\nco.frontyard.cordova.plugin.exoplayer.Player$1#onPlayerError@86\ncom.google.android.exoplayer2.ExoPlayerImpl#handleEvent@611\ncom.google.android.exoplayer2.ExoPlayerImpl$1#handleMessage@125\nandroid.os.Handler#dispatchMessage@106\nandroid.os.Looper#loop@235\nandroid.app.ActivityThread#main@6760\njava.lang.reflect.Method#invoke@-2 NATIVE\ncom.android.internal.os.RuntimeInit$MethodAndArgsCaller#run@493\ncom.android.internal.os.ZygoteInit#main@911\n"

**Comment by frontyard** [comment]
There is not much info in that stack trance and nobody responded to this so I'm closing it for the lack of activity.
