### ISSUE TITLE
Build Failing because of missing exoplayer dependency

### ISSUE THREAD

**Issue by netmikey** [frontyard/cordova-exoplayer-plugin#105]
When building a project with this plugin and `cordova-android@11`, the build is failing because of a missing dependency. Here's the error:

```
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.android.exoplayer:exoplayer:2.6.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer/2.6.1/exoplayer-2.6.1.pom
       - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/exoplayer/2.6.1/exoplayer-2.6.1.pom
       - https://maven.google.com/com/google/android/exoplayer/exoplayer/2.6.1/exoplayer-2.6.1.pom
     Required by:
         project :app
```

And indeed, the Exoplayer 2.9.x Versions are present on none of these repositories. The first 2 don't have that package outright, and `maven.google.com` seems to have been cleaned up because if only shows way newer exoplayer versions starting with v2.13 (see [here](https://maven.google.com/web/index.html#com.google.android.exoplayer:exoplayer)).

My guess is that this plugin will either have to update its exoplayer dependency to a newer version or add some repository to the Gradle build that holds the older versions.

**Edit**
Also noticing that the Versions of this Plugin after 2.5.4 haven't been published to npm, so thats still the [latest version on npm](https://www.npmjs.com/package/cordova-plugin-exoplayer)...?

**Comment by fingunt** [comment]
Hello, I have the same problem here, is there a solution for this problem?

**Comment by bamboolix** [comment]
Same issue here 👍

**Comment by netmikey** [comment]
FYI: I forked this repository and migrated ExoPlayer as good as I could to the newest possible version that still works with the current Cordova versions (ExoPlayer `2.18.1` that is).

https://github.com/netmikey/cordova-plugin-exoplayer

Since this repository seems not to be maintained anymore, I'll switch to my own for now. I don't plan on doing any support though. @frontyard let me know if you'd be interested in a pull request for the ExoPlayer version upgrades.

**Comment by frontyard** [comment]
@netmikey I'd be happy to merge your changes if you send me a PR.

**Comment by guilhermelirio** [comment]
Hi, @netmikey , thanks for the PR.

I tested it here, but when I open the video, the app closes.

My tests:
Cordova: 11.0.0
Cordova-android: 9.1.0 / 11.0.0

**Comment by riksagar** [comment]
I see the same as @guilhermelirio .  Get the following stack dump in logcat.  I'm guessing the call to `view.getPlayer()` in `getExoPlayerView()` is returning `null`.  But I need to get the debugger working before I can be sure.



`08-09 16:27:14.574 11153 11153 D AndroidRuntime: Shutting down VM
08-09 16:27:14.577 11153 11153 E AndroidRuntime: FATAL EXCEPTION: main
08-09 16:27:14.577 11153 11153 E AndroidRuntime: Process: com.roku.web.trc, PID: 11153
08-09 16:27:14.577 11153 11153 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Looper com.google.android.exoplayer2.Player.getApplicationLooper()' on a null object reference
08-09 16:27:14.577 11153 11153 E AndroidRuntime: 	at com.google.android.exoplayer2.ForwardingPlayer.getApplicationLooper(ForwardingPlayer.java:48)
08-09 16:27:14.577 11153 11153 E AndroidRuntime: 	at com.google.android.exoplayer2.ui.StyledPlayerView.setPlayer(StyledPlayerView.java:525)
08-09 16:27:14.577 11153 11153 E AndroidRuntime: 	at co.frontyard.cordova.plugin.exoplayer.LayoutProvider.getExoPlayerView(LayoutProvider.java:55)
08-09 16:27:14.577 11153 11153 E AndroidRuntime: 	at co.frontyard.cordova.plugin.exoplayer.Player.createDialog(Player.java:218)
08-09 16:27:14.577 11153 11153 E AndroidRuntime: 	at co.frontyard.cordova.plugin.exoplayer.Player.createPlayer(Player.java:196)
08-09 16:27:14.577 11153 11153 E AndroidRuntime: 	at co.frontyard.cordova.plugin.exoplayer.Plugin$1.run(Plugin.java:46)
08-09 16:27:14.577 11153 11153 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
08-09 16:27:14.577 11153 11153 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-09 16:27:14.577 11153 11153 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
08-09 16:27:14.577 11153 11153 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
08-09 16:27:14.577 11153 11153 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
08-09 16:27:14.577 11153 11153 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-09 16:27:14.577 11153 11153 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-09 16:27:14.577 11153 11153 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
08-09 16:27:14.585 11153 11153 W om.roku.web.tr: Attempt to remove non-JNI local reference, dumping thread`

**Comment by repotoolsapps** [comment]
Hi, @netmikey , thanks for the PR.

I tested it here, but when I open the video, the app closes.

My tests:
Cordova: 12.0.0
AndroidSDK 33

**Comment by repotoolsapps** [comment]
> I see the same as @guilhermelirio . Get the following stack dump in logcat. I'm guessing the call to `view.getPlayer()` in `getExoPlayerView()` is returning `null`. But I need to get the debugger working before I can be sure.
> 
> `08-09 16:27:14.574 11153 11153 D AndroidRuntime: Shutting down VM 08-09 16:27:14.577 11153 11153 E AndroidRuntime: FATAL EXCEPTION: main 08-09 16:27:14.577 11153 11153 E AndroidRuntime: Process: com.roku.web.trc, PID: 11153 08-09 16:27:14.577 11153 11153 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Looper com.google.android.exoplayer2.Player.getApplicationLooper()' on a null object reference 08-09 16:27:14.577 11153 11153 E AndroidRuntime: at com.google.android.exoplayer2.ForwardingPlayer.getApplicationLooper(ForwardingPlayer.java:48) 08-09 16:27:14.577 11153 11153 E AndroidRuntime: at com.google.android.exoplayer2.ui.StyledPlayerView.setPlayer(StyledPlayerView.java:525) 08-09 16:27:14.577 11153 11153 E AndroidRuntime: at co.frontyard.cordova.plugin.exoplayer.LayoutProvider.getExoPlayerView(LayoutProvider.java:55) 08-09 16:27:14.577 11153 11153 E AndroidRuntime: at co.frontyard.cordova.plugin.exoplayer.Player.createDialog(Player.java:218) 08-09 16:27:14.577 11153 11153 E AndroidRuntime: at co.frontyard.cordova.plugin.exoplayer.Player.createPlayer(Player.java:196) 08-09 16:27:14.577 11153 11153 E AndroidRuntime: at co.frontyard.cordova.plugin.exoplayer.Plugin$1.run(Plugin.java:46) 08-09 16:27:14.577 11153 11153 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:938) 08-09 16:27:14.577 11153 11153 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99) 08-09 16:27:14.577 11153 11153 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:201) 08-09 16:27:14.577 11153 11153 E AndroidRuntime: at android.os.Looper.loop(Looper.java:288) 08-09 16:27:14.577 11153 11153 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:7839) 08-09 16:27:14.577 11153 11153 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method) 08-09 16:27:14.577 11153 11153 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 08-09 16:27:14.577 11153 11153 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 08-09 16:27:14.585 11153 11153 W om.roku.web.tr: Attempt to remove non-JNI local reference, dumping thread`

Have you been able to solve it?

**Comment by riksagar** [comment]
Yes and no!  I added a null check around the `view.setPlayer(new ForwardingPlayer(view.getPlayer())`.  After doing that, I can get playback to start.  The crash was happening on an assert in ExoPlayer.

 _(I'm guessing @netmikey had the Assertion compiled out when he did the fix, so he wasn't getting the crash? [speculation!])_.

So I get past the crash, content starts to play, and I can hear audio playing.  **However**: I don't actually see the video - just a black screen.  This could be related to our UI though.  I'm investigating that now.

Feel free to take the fixes from my branch and let me know your experience:
 - https://github.com/riksagar/cordova-plugin-exoplayer/tree/bugfix/crash-at-player-load

**Comment by repotoolsapps** [comment]
Now there is another problem, when configuring the array controller and
trying to play the video the application also closes. thanks for your
attention

var parameters = {
        url: url,
        userAgent: "",
        aspectRatio: 'FIT_SCREEN', // default is FIT_SCREEN
        hideTimeout: 5000, // Hide controls after this many milliseconds,
default is 5 sec
        autoPlay: true, // When set to false stream will not automatically
start
        seekTo: 10 * 60 * 60 * 1000, // Start playback 10 minutes into
video specified in ms, default is 0
        forwardTime: 30 * 1000, // Amount of time in ms to use when
skipping forward, default is 1 min
        rewindTime: 30 * 1000, // Amount of time in ms to use when skipping
backward, default is 1 min
        audioOnly: false, // Only play audio in the backgroud, default is
false
                         //subtitleUrl: 'http://url.to/subtitle.srt', //
Optional subtitle url
        connectTimeout: 0, // http connect timeout in ms (default is 0)
        readTimeout: 0, // http read timeout in ms (default is 0)
        retryCount: 3, // Number of times datasource will retry the stream
before giving up (default is 3)
        showBuffering: true, // When buffering, player will show indicator
at the top of the screen, default is false
        controller: { // If this object is not present controller will not
be visible
            streamImage: imagen,
            streamTitle: nombre.substring(0, 40),
            streamDescription: descripcion.substring(0, 65),
            hideProgress: false, // Hide entire progress timebar
            hidePosition: false, // If timebar is visible hide current
position from it
            hideDuration: false, // If timebar is visible Hide stream
duration from it
            controlIcons: {
                //'exo_rew': '
http://simpleicon.com/wp-content/uploads/play1-256x256.png', // Set to null
to remove the button from the player
                //'exo_play': '
http://simpleicon.com/wp-content/uploads/play1-256x256.png',
                //'exo_pause': '
http://simpleicon.com/wp-content/uploads/play1-256x256.png',
                //'exo_ffwd': '
http://simpleicon.com/wp-content/uploads/play1-256x256.png', // Buttons not
included in configuration will show up as default ExoPlayer buttons
            },
            textColor: '#ffffffff', // These colors can be any valid
Android color
            buttonsColor: '#ffffffff', // This example uses hex values
including alpha (first byte)
            bufferingColor: '#ff0000ff' // Alpha of 'ff' makes it 100%
opaque
        }
    }

**Comment by riksagar** [comment]
Did you figure out your issue with the "array controller".  Not sure what that is.

I wrote a test app with just [my patched cordova-plugin-android](https://github.com/riksagar/cordova-plugin-exoplayer/tree/bugfix/crash-at-player-load).  I was able to playback a plain MP4 file and a [DASH stream](https://dash.akamaized.net/akamai/bbb_30fps/bbb_30fps.mpd) (from dash-if site).

(Video and audio both played fine in both cases)

**Comment by jamtechdev** [comment]
Hey,

Has anyone figured out anything on this ?
We have tried almost all available forks of this plugin but to no avail, this app keeps crashing while reaching the exoplayer related section.

Also @frontyard, we aren't able to add the newest version of the plugin, it still defaults to 2.5.4, and if we specify a fixed version it just doesn't recognize that version.

![image](https://github.com/frontyard/cordova-plugin-exoplayer/assets/30105044/a2834a2e-d68d-4df9-9560-defa4fe54997)


An update of the README is much needed

**Comment by riksagar** [comment]
Hey, 

I made some additional changes to my [crash-at-player-load](https://github.com/riksagar/cordova-plugin-exoplayer/tree/bugfix/crash-at-player-load) branch.  I've been testing it locally for a while with no issue.

I'll post a pull-request to @frontyard in the next few days, in addition to my test app.

You might try download the ZIP of my branch locally and `cordova plugin add ...` with that.

**Comment by repotoolsapps** [comment]
Thank you for reporting, I am currently working on a libvlc plugin. It
supports more video formats and so on. But I still have problems with App
crashes, when the player is loading the video and I close the player or it
is a slow url and I close the player. And the truth is that I can't move
forward from there.

**Comment by riksagar** [comment]
Can you share a stack trace from the crash?

libvlc would be interesting, but doesn't support DRM?

**Comment by frontyard** [comment]
We can merge changes from @netmikey and @riksagar back into original project. I just don't have enough time to test these changes, so if we do it as a major version change people can test without affecting their production code.
