### ISSUE TITLE
compatible with the latest version Cordova 12?

### ISSUE THREAD

**Issue by rcasunshare** [frontyard/cordova-exoplayer-plugin#108]
Is this plugin compatible with the latest version Cordova 12?

https://cordova.apache.org/announcements/2023/05/22/cordova-android-12.0.0.html

**Comment by frontyard** [comment]
It's not just cordova version, there's also cordova-android, android sdk version, expoplayer version and possibly few more things I'm forgeting. So the short answer is, try it and if it works great :-)
