### ISSUE TITLE
Force start in landscape mode

### ISSUE THREAD

**Issue by utgMarketing** [frontyard/cordova-exoplayer-plugin#99]
My Cordova app is locked in portrait mode.  Is it possible to force the player to start in landscape mode?  

Now I use screen.orientation.lock("landscape") when starting the player and screen.orientation.lock("portrait") when stopping playback.  

But this is not safe, if there is an error, the application will remain in landscape mode.

**Comment by frontyard** [comment]
If you find a solution please submit a pull request.
